#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
root = "../../"
tmp_dir = "cmd/core/tmp"

[build]
bin = "./bin/core"
cmd = "go build -o bin/core core.go"
include_dir = ["cmd/core", "internal/app/core", "internal/pkg", "pb"]
