# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/health/v1/health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.health.v1 import health_check_request_pb2 as proto_dot_health_dot_v1_dot_health__check__request__pb2
from proto.health.v1 import health_check_response_pb2 as proto_dot_health_dot_v1_dot_health__check__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/health/v1/health.proto\x12\thealth.v1\x1a*proto/health/v1/health_check_request.proto\x1a+proto/health/v1/health_check_response.proto2R\n\x06Health\x12H\n\x05\x43heck\x12\x1d.health.v1.HealthCheckRequest\x1a\x1e.health.v1.HealthCheckResponse\"\x00\x42\x33Z1github.com/KaikaikaiFang/divine-agent/core/healthb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/KaikaikaiFang/divine-agent/core/health'
  _globals['_HEALTH']._serialized_start=132
  _globals['_HEALTH']._serialized_end=214
# @@protoc_insertion_point(module_scope)
