#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json
root = "../../"
tmp_dir = "cmd/datapark/tmp"

[build]
bin = "./bin/datapark"
cmd = "go build -o bin/datapark datapark.go"
include_dir = ["cmd/datapark", "internal/app/datapark", "internal/pkg", "pb"]
